#!/bin/bash -l
echo "Starting notebook server with UID: $NB_UID and GID: $NB_GID and user: $NB_USER"
useradd -u $NB_UID $NB_USER
sudo useradd -u $NB_UID $NB_USER

exec "$@"

source /etc/profile.d/init_conda.sh