# The base JupyterHub image. Sets up initial software & dependencies
# Dockerfile to build on top of - Using Ubuntu 22.04
FROM ubuntu:24.04 AS base

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Setup environment
ENV CONDA_ENV=cirrus-base \
    CONDA_VER='25.3.0-1' \
    # Install conda in the same place repo2docker does
    CONDA_DIR=/srv/conda \
    CONDA_USRDIR=/srv/base-conda \
    # Tell apt-get to not block installs by asking for interactive human input
    DEBIAN_FRONTEND=noninteractive \
    # Set username, uid and gid (same as uid) of non-root user the container will be run as
    NB_USER=jovyan \
    NB_UID=1000 \
    NB_GID=1000 \
    # Use /bin/bash as shell, not the default /bin/sh (arrow keys, etc don't work then)
    SHELL=/bin/bash \
    # Setup locale to be UTF-8, avoiding gnarly hard to debug encoding errors
    LANG=C.UTF-8  \
    LC_ALL=C.UTF-8 

# All env vars that reference other env vars need to be in their own ENV block
# Home directory of our non-root user
ENV NB_PYTHON_PREFIX=${CONDA_USRDIR}/envs/${CONDA_ENV} \
    HOME=/home/${NB_USER}

# Add both our notebook env as well as default conda installation to $PATH
# Thus, when we start a `python` process (for kernels, or notebooks, etc),
# it loads the python in the notebook conda environment, as that comes
# first here.
ENV PATH=${CONDA_DIR}/bin:${NB_PYTHON_PREFIX}/bin:${PATH}
#ENV PATH=${CONDA_DIR}/bin:${PATH}

# Ask dask to read config from ${CONDA_DIR}/etc rather than
# the default of /etc, since the non-root jovyan user can write
# to ${CONDA_DIR}/etc but not to /etc
ENV DASK_ROOT_CONFIG=${CONDA_USRDIR}/etc
#ENV DASK_ROOT_CONFIG=${CONDA_DIR}/etc

# Copy in a file that contains all apt packages to install in the image
COPY apt.txt apt.txt

# Install apt packages
RUN echo "Installing Apt-get packages..." \
    && apt-get update --fix-missing > /dev/null \
    && apt-get install -y apt-utils wget zip tzdata > /dev/null \
    && xargs -a apt.txt apt-get install -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    
###
# Copy a script that we will use to correct permissions after running certain commands
###
COPY scripts/fix-permissions /usr/local/bin/fix-permissions

# Change permissions on the script so it can be run
RUN chmod a+rx /usr/local/bin/fix-permissions

# Create NB_USER with name jovyan user with UID=1000 and in the 'users' group
# and make sure these dirs are writable by the `users` group.
RUN echo "Setting up ${NB_USER} user..." \
    # Remove the default ubuntu user if it exists
    && (userdel -r ubuntu 2>/dev/null || true) \
    # Create a group for the user to be part of, with gid same as uid
    && groupadd --gid ${NB_UID} ${NB_USER} \
    # Create non-root user, with given gid, uid and create $HOME
    && useradd --create-home --gid ${NB_UID} --no-log-init --uid ${NB_UID} ${NB_USER} \
    # Make sure that /srv is owned by non-root user, so we can install things there
    && chown -R ${NB_USER}:${NB_USER} /srv

# Create the directories where conda environments are going to be installed
RUN mkdir -p "${CONDA_DIR}" && \
    #mkdir -p "${CONDA_USRDIR}" && \
    fix-permissions "${CONDA_DIR}" && \
    #fix-permissions "${CONDA_USRDIR}" && \
    fix-permissions "/home/${NB_USER}"

# Add TZ configuration - https://github.com/PrefectHQ/prefect/issues/3061
ENV TZ=UTC
# ========================

# Install latest mambaforge in ${CONDA_DIR}
RUN echo "Installing Mambaforge..." \
    && URL="https://github.com/conda-forge/miniforge/releases/download/${CONDA_VER}/Miniforge3-${CONDA_VER}-Linux-x86_64.sh" \
    && wget --quiet ${URL} -O installer.sh \
    && /bin/bash installer.sh -u -b -p ${CONDA_DIR} \
    && rm installer.sh \
    && mamba install conda-lock jupyterhub==5.2.1 notebook r-irkernel conda-forge::nb_conda_kernels -y \
    && mamba clean -afy \
    # After installing the packages, we cleanup some unnecessary files
    # to try reduce image size - see https://jcristharif.com/conda-docker-tips.html
    # Although we explicitly do *not* delete .pyc files, as that seems to slow down startup
    # quite a bit unfortunately - see https://github.com/2i2c-org/infrastructure/issues/2047
    && find ${CONDA_DIR} -follow -type f -name '*.a' -delete \
    # Fix permissions
    && fix-permissions "${CONDA_DIR}" \
    && fix-permissions "/home/${NB_USER}"

# Run conda activate each time a bash shell starts, so users don't have to manually type conda activate
# Note this is only read by shell, but not by the jupyter notebook - that relies
# on us starting the correct `python` process, which we do by adding the notebook conda environment's
# bin to PATH earlier ($NB_PYTHON_PREFIX/bin)
RUN echo ". ${CONDA_DIR}/etc/profile.d/conda.sh ; conda activate ${CONDA_ENV}" > /etc/profile.d/init_conda.sh

# Install code-server for VSCode kernel
RUN curl -fsSL https://code-server.dev/install.sh | sh && \
    # Copy VS Code icon to Jupyter's static directory
    mkdir -p /usr/local/share/jupyter/lab/static/vscode && \
    cp /usr/lib/code-server/lib/vscode/resources/server/favicon.ico /usr/local/share/jupyter/lab/static/vscode/ && \
    fix-permissions "/home/${NB_USER}"

# Change to /tmp to work out
WORKDIR /tmp

# Copy pip and conda packages in to tmp
COPY conda/requirements.txt /tmp/

# Install pip packages
RUN ${CONDA_DIR}/bin/pip install --no-cache -r requirements.txt

# Copy the initial condarc file over to define conda congiruation
COPY --chown="${NB_UID}:${NB_GID}" configs/.condarc "${CONDA_DIR}/.condarc"

# Copy the jupyter configuration
COPY configs/jupyter_server_config.py /etc/jupyter/jupyter_server_config.py
# Used to allow user deletions of folders and contents
RUN sed -i 's/c.FileContentsManager.delete_to_trash = False/c.FileContentsManager.always_delete_dir = True/g' /etc/jupyter/jupyter_server_config.py

# Copy default bashrc
COPY configs/.bashrc /etc/bash.bashrc

# Copy the final condarc file over to define conda congiruation
COPY --chown="${NB_UID}:${NB_GID}" configs/.condarc "${CONDA_DIR}/.condarc"

# Add VSCode icon to the directory the kernel expects it
RUN mkdir -p /srv/conda/share/jupyter/lab/static/icons && \
    curl -L https://code.visualstudio.com/assets/branding/visual-studio-code-icons.zip \
         -o /tmp/vscode-icons.zip && \
    unzip -j /tmp/vscode-icons.zip "*/vscode.svg" -d /srv/conda/share/jupyter/lab/static/icons/ && \
    rm /tmp/vscode-icons.zip

# Make the conda environments we install read only and executable for the user
# They can run the environments but will get permission denied when trying to make changes
# New environments are installed to /home/jovyan/.jupyter with write permissions for the users
RUN chown root:root /srv/*   

# Cleanup files that were already installed
RUN rm -rf /tmp/requirements.txt

# Set the default user to jovyan and make home /hom/jovyan
USER ${NB_USER}
WORKDIR ${HOME}

# Copy over the start script with the correct permissions assigned
COPY --chmod=755 /scripts/start /srv/start

# Expose the port Jupyter runs on
EXPOSE 8888

# The Entrypoint is the /srv/start script
# ENTRYPOINT ["/srv/start"]


FROM base AS cpu-nb
#cpu notebook
LABEL org.opencontainers.image.title="NSF NCAR CIRRUS JupyterHub Base Notebook Image"
LABEL org.opencontainers.image.description="JupyterHub notebook server with Python and R environments"
LABEL org.opencontainers.image.source="https://github.com/NCAR.cirrus-jhub-images"
LABEL org.opencontainers.image.licenses="MIT"

# Setup environment
ENV CONDA_ENV=cirrus-base \
    CONDA_VER='25.3.0-1' \
    CONDA_DIR=/srv/conda \
    CONDA_USRDIR=/srv/base-conda \
    DEBIAN_FRONTEND=noninteractive \
    NB_USER=jovyan \
    NB_UID=1000 \
    NB_GID=1000 \
    SHELL=/bin/bash \
    LANG=C.UTF-8  \
    LC_ALL=C.UTF-8 

# Home directory of our non-root user
ENV HOME=/home/${NB_USER}

USER root
WORKDIR /tmp
# Copy pip and conda packages in to tmp
COPY conda/requirements.txt conda/cirrus-base.yml conda/r-4.4.yml /tmp/

RUN mamba env create --prefix /srv/base-conda/cirrus-base -f cirrus-base.yml \
    && mamba env create --prefix /srv/base-conda/r-4.4 -f r-4.4.yml \
    && mamba clean -afy 
    # Fix permissions
#RUN fix-permissions "${CONDA_DIR}" \
#    && fix-permissions "${CONDA_USRDIR}" \
#    && fix-permissions "/home/${NB_USER}"

# Cleanup files that were already installed
RUN rm -rf /tmp/cirrus-base.yml && \
    rm -rf /tmp/r-4.4.yml && \
    rm -rf /tmp/requirements.txt

USER ${NB_USER}
WORKDIR ${HOME}

ENTRYPOINT ["/srv/start"]

#cuda notebook that puts cuda on top of the cirrus-base cpu
#further used as the base for the torch and tf nb
FROM base AS gpu-nb

ENV CONDA_ENV=cirrus-gpu  \
    CUDNN_VERSION=9.10.1.4 \
    CUDA_VERSION=12 \
    PIP_EXTRA_INDEX_URL='https://pypi.nvidia.com'

ENV NB_PYTHON_PREFIX=${CONDA_USRDIR}/${CONDA_ENV}
USER root
WORKDIR /tmp

# Copy pip and conda packages in to tmp
COPY conda/cirrus-gpu-base.yml /tmp/

RUN apt update && apt install -y xz-utils nvidia-cuda-toolkit nvidia-cuda-dev

COPY conda/requirements-gpu.txt conda/cirrus-tensorflow-base.yml /tmp/

RUN wget https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/linux-x86_64/cudnn-linux-x86_64-${CUDNN_VERSION}_cuda${CUDA_VERSION}-archive.tar.xz \
    && tar -xvf cudnn-linux-x86_64-${CUDNN_VERSION}_cuda${CUDA_VERSION}-archive.tar.xz \
    && cp cudnn-*-archive/include/cudnn*.h /usr/lib/cuda/include \
    && cp -P cudnn-*-archive/lib/libcudnn* /usr/lib/cuda/lib64 \
    && chmod a+r /usr/lib/cuda/include/cudnn*.h /usr/lib/cuda/lib64/libcudnn* \
    && rm -rf cudnn-linux-x86_64-${CUDNN_VERSION}_cuda${CUDA_VERSION}-archive.tar.xz cudnn-*-archive


# Setup LD_LIBRARY_PATH to include CUDA libraries
RUN echo 'export LD_LIBRARY_PATH=${CONDA_USRDIR}/${CONDA_ENV}/lib/:${CONDA_DIR}/lib/:/usr/lib/cuda/lib64' > ${CONDA_DIR}/etc/conda/activate.d/env_vars.sh && \
    # Add CUDA environment variables
    echo 'export CUDA_HOME=/usr/lib/cuda' >> ${CONDA_DIR}/etc/conda/activate.d/env_vars.sh && \
    echo 'export PATH=$PATH:/usr/lib/cuda/bin' >> ${CONDA_DIR}/etc/conda/activate.d/env_vars.sh && \
    # Add XLA flags for TensorFlow
    printf 'export XLA_FLAGS=--xla_gpu_cuda_data_dir=${CONDA_DIR}/lib/\n' >> ${CONDA_DIR}/etc/conda/activate.d/env_vars.sh

# Install pip packages into base jhub env
RUN ${CONDA_DIR}/bin/pip install --no-cache -r /tmp/requirements-gpu.txt

# Create the conda envs with mamba to increase installation speed
RUN mamba env create --prefix ${CONDA_USRDIR}/${CONDA_ENV} -f cirrus-gpu-base.yml \
    && mamba clean -afy 
    # Fix permissions
#RUN fix-permissions "${CONDA_DIR}" \
#    && fix-permissions "${CONDA_USRDIR}" \
#    && fix-permissions "/home/${NB_USER}"

USER ${NB_USER}
WORKDIR ${HOME}
ENTRYPOINT ["/srv/start"]


#TF notebook
FROM gpu-nb AS tf-nb

USER root

LABEL org.opencontainers.image.title="NSF NCAR CIRRUS JupyterHub Tensorflow Notebook Image"
LABEL org.opencontainers.image.description="JupyterHub notebook server with cuda tensorflow"
LABEL org.opencontainers.image.source="https://github.com/NCAR.cirrus-jhub-images"
LABEL org.opencontainers.image.licenses="MIT"

ENV CONDA_ENV=cirrus-gpu 

RUN mamba install -n ${CONDA_ENV} -f /tmp/cirrus-tensorflow-base.yml && \
    mamba clean -afy
USER ${NB_USER}
WORKDIR ${HOME}
ENTRYPOINT ["/srv/start"]


#Torch notebook
FROM gpu-nb AS torch-nb

USER root

LABEL org.opencontainers.image.title="NSF NCAR CIRRUS JupyterHub PyTorch Notebook Image"
LABEL org.opencontainers.image.description="JupyterHub notebook server with cuda pytorch"
LABEL org.opencontainers.image.source="https://github.com/NCAR.cirrus-jhub-images"
LABEL org.opencontainers.image.licenses="MIT"

ENV CONDA_ENV=cirrus-gpu 

COPY conda/cirrus-pytorch-base.yml /tmp/

RUN mamba install -n ${CONDA_ENV} -f /tmp/cirrus-pytorch-base.yml && \
    mamba clean -afy
USER ${NB_USER}
WORKDIR ${HOME}
ENTRYPOINT ["/srv/start"]