# This workflow tests changes to the conda environment yaml files
# Set the workflow name
name: Test Package YML Files

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/base-notebook/ path
on:
  push:
    paths:
      - images/*/packages/*.yml
    branches:
      - dev

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  test-conda-envs:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: gh-arc-ccpp-images
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Containerfile
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1
        with:
          files: images/*/packages/*.yml
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          python-version: '3.10'
      - name: Create Conda environments
        shell: bash -el {0}
        run: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Creating environment from $file"
            conda env create -f $file
            done