# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-notebook directory and image
# Set the workflow name
name: PyTorch Build Test

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/base-notebook/ path
on:
  push:
    paths:
      - images/gpu-pyt-notebook/**
    branches:
      - dev

env:
  BRANCH_NAME: ${{ github.ref_name }}

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  test-build-pytorch-nb:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: gha-runner-cirrus-jhub-images
    # Set the steps to take in order
    steps:
      # Checkout the github repo used to build the Container Image
      - name: Check out the repo
        uses: actions/checkout@v4
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Build pytorch notebook image
        run: |
          docker buildx create --use --driver=remote tcp://buildkitd.arc-systems.svc.ml-cluster.local:1234
          docker buildx build --load -f images/gpu-pyt-notebook/Containerfile -t hub.k8s.ucar.edu/cirrus-jhub/cirrus-jhub-pytorch:${{ steps.date.outputs.date }} images/gpu-pyt-notebook/.
      - name: Create pull request to merge dev in to main
        run: gh pr view ${{ env.BRANCH_NAME }} && gh pr reopen ${{ env.BRANCH_NAME }} || gh pr create -B main -H ${{ env.BRANCH_NAME }}  --title 'Test build successful. Merge PyTorch notebook update from dev into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}