# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-image directory and image
# Set the workflow name
name: JHub Base Build & Push

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/base-image/ path
on:
  workflow_dispatch: 
  push:
    paths:
      - images/base-image/**
    branches:
      - main

permissions:
  contents: read

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  build-push-base-image:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: gha-runner-cirrus-jhub-images
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Container Image
      - name: Check out the repo
        uses: actions/checkout@v4
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Login to Harbor
        run: docker login hub.k8s.ucar.edu -u ${{ secrets.HARBOR_LOGIN }} -p ${{ secrets.HARBOR_SECRET }}
      - name: Build image
        run: |
          docker buildx create --use --driver=remote tcp://buildkitd.arc-systems.svc:1234
          docker buildx build --push -f images/base-image/Containerfile -t hub.k8s.ucar.edu/cirrus-jhub/cirrus-jhub-base:${{ steps.date.outputs.date }} images/base-image/.
